### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by Surgo**
Use django's six module to support python3

* [x] add python 2.7 specific tox requirement.
* [x] drop 3.2 **and 3.3**
* [x] fix code
* [ ] refactoring (next PR)

### CODE REVIEW

**Comment by 4word** [comment]
Any word on this? I would love to see this get merged in, I have been using this library for a few months at my company and had to do all the py3 conversions already, and would love to get us on the master branch rather than our own internal one.

**Comment by JBKahn** [comment]
Just on my way home right now, then I'll take a look! If you have any other
feedback on the package, I'd love to hear it.

**Comment by JBKahn** [comment]
Ya this looks great!

**Comment by Surgo** [comment]
thank you so much :)

**Pull request merged**
