### PR TITLE
toxifications

### PR DESCRIPTION
**Pull request by JBKahn**

### CODE REVIEW

**Comment by JBKahn** [comment]
- [ ] add python 2.7 specific tox requirement.
- [ ] drop 3.2
- [ ] fix code

**Comment by Surgo** [comment]
Is this stopped?

**Comment by JBKahn** [comment]
I was in the middle of a bunch of other things but I can pick it back up.

**Comment by Surgo** [comment]
ok, thank you :)

I made pr #23 to this branch to fix task list. I hope this will help.
and, why don't you use travis-ci? travis-ci support to run test on [python3 nightly](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against)

**Comment by JBKahn** [comment]
good call, I'll take a quick look at this tomorrow night and probably just merge it right in. Looks like great work :)

**Comment by JBKahn** [comment]
I will look into detoxing after this, I just need to look at the equivalent way to handle also testing the different versions of Django.

**Comment by JBKahn** [comment]
Alright I'm good to go on this for now, I'll merge it in.

**Pull request merged**
