### PR TITLE
Added manager and queryset for automatic shard selection in the router

### PR DESCRIPTION
**Pull request by 4word**
This is untested, just wanted to get feedback on how I could use hints derived from the get, filter, and exclude functions within the router so that you no longer have to define "using(db)" if you passed in the shard key.

### CODE REVIEW

**Comment by 4word** [comment]
So there is one main thing needed to make the new hints usable: a way to get the field that being used to shard by. In the project's examples, this would be the 'user_id' field on the sharded model. Unfortunately, right now, there is no way to check which field is the one that we should use to select the shard (that I can find), and I don't want to assume it will be the user_id for everybody, other people might shard by some other model.

**Comment by 4word** [comment]
Updated the router and decorator to handle a sharded_by_field attribute that will let the custom manager and router automatically route queries without using() and without having to have an existing instance (for example, filter(user_id=123) will automatically send the query to the shard with the data for user 123 without having to specify using(shard_for_123) or similar)

**Comment by JBKahn** [comment]
Closed?

**Comment by 4word** [comment]
Just closed it until I can write up unit tests, I am not a fan of opening
up PRs without them being tested so I closed it until I get time for that.

You can see updates in my fork + branch for the custom manager and
queryset:
https://github.com/4word/django-sharding/tree/shard-by-manager-and-router .
Hoping to get to some unit tests today or tomorrow.

I am moving over our postgres custom field that deals with shard IDs right
now, and when that is done I will open a pull request for it too.
Unfortunately, making some of the things "automatic" that we do manually so
that its library friendly is harder than I thought it would be.

On Mon, May 2, 2016 at 2:02 PM, Joseph Kahn <notifications@github.com>
wrote:

> Closed?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/JBKahn/django-sharding/pull/25#issuecomment-216362674>
>



-- 
Titus Peterson

**Comment by JBKahn** [comment]
K, let me know if you hit any roadblocks.

**Pull request closed without merging**
